from pathlib import Path
import glob
import pandas as pd
import numpy as np
from collections import defaultdict
import os

######## RUN THIS TO CREATE DAG ########
# snakemake --cores 4 --dag 2>/dev/null | grep -v "Including" | dot -Tpdf > dag.pdf
########################################


configfile: "config.yaml"

ar6_clim_factors = ['prec','temp_min','temp_max','temp_avg']
tread_clim_factors = ['prec','temp_min','temp_max','rel_humid','wind_spd']
gwl_scenarios = ['GWL1.5','GWL2.0','GWL3.0','GWL4.0']
ssp_scenarios = ['historical','ssp126','ssp245','ssp370','ssp585']
branches = config["branches"]

# Locate all WORK directories 
SSPRCP_MAIN_DIR = Path(workflow.basedir).resolve()
SSPRCP_BASE_DIR = SSPRCP_MAIN_DIR.parents[0]
SCRIPTS_DIR = SSPRCP_MAIN_DIR / "src"


###############################################################################
# Directories
###############################################################################

SSPRCP_WORK_DIR = SSPRCP_MAIN_DIR
DATA_DIR = SSPRCP_WORK_DIR / "data"
RAW_DIR = DATA_DIR / "raw"
INTERIM_DIR = DATA_DIR / "interim"
PROCESSED_DIR = DATA_DIR / "processed"

GWL_RAW_DIR   = RAW_DIR / "GWL"
AR6_RAW_DIR   = RAW_DIR / "AR6"
AR6_INTERIM_DIR = INTERIM_DIR / "AR6"
TREAD_RAW_DIR = RAW_DIR / "TREAD"
NETCDF_DIR    = PROCESSED_DIR / "NetCDF"
GWL_NETCDF_DIR = NETCDF_DIR / "GWL_NetCDF"
AR6_NETCDF_DIR = NETCDF_DIR / "AR6_NetCDF"
TREAD_NETCDF_DIR = NETCDF_DIR / "TREAD_NetCDF"

FIGURES_DIR = SSPRCP_WORK_DIR / "figures"

# Create directories
dirs_to_create = [
    RAW_DIR,
    INTERIM_DIR,
    AR6_INTERIM_DIR,
    PROCESSED_DIR,
    GWL_RAW_DIR,
    AR6_RAW_DIR,
    TREAD_RAW_DIR,
    NETCDF_DIR,
    GWL_NETCDF_DIR,
    AR6_NETCDF_DIR,
    TREAD_NETCDF_DIR,
    FIGURES_DIR
]
for d in dirs_to_create:
    d.mkdir(parents=True, exist_ok=True)

GWL_outputs = [GWL_NETCDF_DIR / "gwl_all.nc",
        GWL_NETCDF_DIR / "gwl_all_sliced.nc",
        GWL_NETCDF_DIR / "gwl_all_sliced.tsv"]

AR6_outputs = [AR6_NETCDF_DIR / "AR6_all.nc",
        AR6_NETCDF_DIR / "AR6_all_sliced.nc",
        AR6_NETCDF_DIR / "AR6_all_sliced.tsv"]

TREAD_outputs = [TREAD_NETCDF_DIR / "TREAD_all.nc",
        TREAD_NETCDF_DIR / "TREAD_all_sliced.nc",
        TREAD_NETCDF_DIR / "TREAD_all_sliced.tsv"]
###############################################################################
# Rule all: final targets
###############################################################################
rule all:
    input:
        *GWL_outputs if "GWL" in branches else [],
        *AR6_outputs if "AR6" in branches else [],
        *TREAD_outputs if "TREAD" in branches else []



###############################################################################
# Include branch rules
###############################################################################
for branch in branches:
    print(f"Including rules for branch: {branch}")
    include: f"rules/{branch}.smk"

