
FROM continuumio/miniconda3:latest

WORKDIR /app
COPY . .

RUN chmod +x /app/start_notebook.sh

RUN conda create -n myenv python=3.10

RUN /bin/bash -c "source activate myenv && python --version"
RUN /bin/bash -c "source activate myenv && conda install -c conda-forge pywin32"
RUN /bin/bash -c "source activate myenv && pip install -r requirements.txt"
RUN /bin/bash -c "source activate myenv && conda install -c conda-forge jupyter"
COPY start_notebook.sh /app/start_notebook.sh
RUN chmod +x /app/start_notebook.sh

CMD ["/bin/bash", "-c", "source activate myenv && /app/start_notebook.sh"]
