# ============================================================
# STGAT config — SEA dengue baseline
# ---------------------------------------------------------------------------

task:          regression # classification
target_column: IR         # target variable; "outbreak_risk" for classification 
data_path: "/home/patwuch/Documents/projects/Chuang-Lab-TMU/machine-learning-module/data/processed/SEA_dengue_env_monthly_2011-2018.csv"

log_transform: true       # log transforms IR if applicable; ignored for classification 

# Feature groups
# ---------------------------------------------------------------------------

env_vars:
  - precipitation_sum
  - temperature_2m_mean
  - temperature_2m_max_mean
  - temperature_2m_min_mean
  - potential_evaporation_sum_mean
  - total_evaporation_sum_mean
  - evaporation_from_bare_soil_sum_mean
  - evaporation_from_open_water_surfaces_excluding_oceans_sum_mean
  - evaporation_from_the_top_of_canopy_sum_mean
  - evaporation_from_vegetation_transpiration_sum_mean
  - LST_Day_1km_mean
  - LST_Night_1km_mean
  - NDVI_mean
  - EVI_mean

lulc_vars: 
  - LC_Type1_pct_class1
  - LC_Type1_pct_class2
  - LC_Type1_pct_class3
  - LC_Type1_pct_class4
  - LC_Type1_pct_class5
  - LC_Type1_pct_class6
  - LC_Type1_pct_class7
  - LC_Type1_pct_class8
  - LC_Type1_pct_class9
  - LC_Type1_pct_class10
  - LC_Type1_pct_class11
  - LC_Type1_pct_class12
  - LC_Type1_pct_class13
  - LC_Type1_pct_class14
  - LC_Type1_pct_class15
  - LC_Type1_pct_class16
  - LC_Type1_pct_class17


lag_steps: [1, 2, 3]   # applied to variables with monthly granularity during preprocessing
add_lag_IR: false        # whether to add one-month lag for the target variable

# ---------------------------------------------------------------------------
# Train / val / test split
# ---------------------------------------------------------------------------
split:
  test_months: 12       # number of months reserve as true test until the end of the data (i.e., 2018-12) 
  val_fraction: 0.15    # last 15% of non-test sequences

